### ISSUE TITLE
How can I get valid JSON file with this plugin?

### ISSUE THREAD

**Issue by ValeryIvanov** [crissdev/gulp-props#3]
Currently it makes a .js file and inside is 

var config = config || {};
config['i18n.

...and so on

But I dont understand how can I create valid JSON file.

My gulp task is like that

gulp.task('i18n', function () {
    gulp.src('./i18n/*.properties')
        .pipe(props())
        .pipe(gulp.dest('./i18n/'));
});

**Comment by ValeryIvanov** [comment]
Okay I looked in the source code and realized that if I write

.pipe(props({namespace : ""}))

then it will make a JSON file, otherwise Javascript file. I suggest you to improve README file, because I could not understand that from it.

Thanks for great plugin! (Y)

**Comment by crissdev** [comment]
@ValeryIvanov Thanks! I agree and I'll update the README.md file in a bit.
